force-app/main/default/objects/Status_Report__c/Status_Report__c.object-meta.xml
<CustomObject>
    <description>Capture inventory for a given Department and patient details. New inventory items or patient statuses can be added and tracked depending on the need of the Department</description>
    <label>Status Report</label>
    <nameField>
        <label>Status Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>These are the individual status report records by the core data point being tracked.</description>
    <inlineHelpText>These are the individual status report records by the core data point being tracked.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Report_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Report_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>COVID Like</fullName>
    </customValue>
    <customValue>
        <fullName>Presumptive COVID</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Positive</fullName>
        <label>COVID Positive</label>
    </customValue>
    <customValue>
        <fullName>Comorbidity</fullName>
    </customValue>
    <customValue>
        <fullName>Health Care Staff COVID Positive</fullName>
    </customValue>
    <customValue>
        <fullName>Age Range</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilator Beds</fullName>
    </customValue>
    <customValue>
        <fullName>Anaesthesia Machines</fullName>
    </customValue>
    <customValue>
        <fullName>N95 Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Face Shields</fullName>
    </customValue>
    <customValue>
        <fullName>Hoods</fullName>
    </customValue>
    <customValue>
        <fullName>Level 3 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Level 4 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Coveralls</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Fit Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Nitrile)</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Sterile)</fullName>
    </customValue>
    <customValue>
        <fullName>Hand Sanitizer</fullName>
    </customValue>
    <customValue>
        <fullName>Disinfectant</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Goggles</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Glasses</fullName>
    </customValue>
    <customValue>
        <fullName>Shoe Covers</fullName>
    </customValue>
    <masterLabel>Status Report Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StatusReportTypePicklist.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @description Class to get picklist values for the Type__c field of the status_report__c object
 * @author  Heather Purvis, Traction on Demand
 * @date    2020-03-18
 */
global class StatusReportTypePicklist extends VisualEditor.DynamicPickList{

    global override VisualEditor.DataRow getDefaultValue(){
        Schema.DescribeFieldResult fieldResult = Status_Report__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow(picklistEntries[0].Label, picklistEntries[0].value);
        return defaultValue;
    }
    global override VisualEditor.DynamicPickListRows getValues() {
        Schema.DescribeFieldResult fieldResult = Status_Report__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();

        VisualEditor.DynamicPickListRows  myValues = new VisualEditor.DynamicPickListRows();
        for(Schema.PicklistEntry picklistEntry : picklistEntries) {
            myValues.addRow(new VisualEditor.DataRow(picklistEntry.Label, picklistEntry.value));
        }

        return myValues;
    }
}