force-app/main/default/objects/Account/fields/Beds_Available__c.field-meta.xml
<CustomField>
    <fullName>Beds_Available__c</fullName>
    <label>Beds Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Beds_in_Use__c.field-meta.xml
<CustomField>
    <fullName>Beds_in_Use__c</fullName>
    <label>Beds in Use</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Beds_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Beds_Inactive__c</fullName>
    <description>For example a closed ward that isn&#39;t staffed.</description>
    <inlineHelpText>For example a closed ward that isn&#39;t staffed.</inlineHelpText>
    <label>Beds Inactive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</description>
    <inlineHelpText>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On staff</fullName>
            </value>
            <value>
                <fullName>Isolation - COVID symptoms/exposure</fullName>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>COVID positive</fullName>
                <isActive>false</isActive>
                <label>COVID positive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Report__c/Status_Report__c.object-meta.xml
<CustomObject>
    <description>Capture inventory for a given Department and patient details. New inventory items or patient statuses can be added and tracked depending on the need of the Department</description>
    <label>Status Report</label>
    <nameField>
        <label>Status Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Report__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of data being tracked e.g. Equipment, Supplies</description>
    <inlineHelpText>The type of data being tracked</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Report_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>The amount of what you are tracking</description>
    <inlineHelpText>The amount</inlineHelpText>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The location this status report is for.</description>
    <inlineHelpText>The location this status report is for.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Status Reports</relationshipLabel>
    <relationshipName>Status_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Inactive can refer to a bed that&#39;s in an unstaffed ward and not available yet.</description>
    <inlineHelpText>Inactive can refer to a bed that&#39;s in an unstaffed ward and not available yet.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In use</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>These are the individual status report records by the core data point being tracked.</description>
    <inlineHelpText>These are the individual status report records by the core data point being tracked.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Report_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Report_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Patient</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Status Report Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Status_Report_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>COVID Like</fullName>
    </customValue>
    <customValue>
        <fullName>Presumptive COVID</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Positive</fullName>
        <label>COVID Positive</label>
    </customValue>
    <customValue>
        <fullName>Comorbidity</fullName>
    </customValue>
    <customValue>
        <fullName>Health Care Staff COVID Positive</fullName>
    </customValue>
    <customValue>
        <fullName>Age Range</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilator Beds</fullName>
    </customValue>
    <customValue>
        <fullName>Anaesthesia Machines</fullName>
    </customValue>
    <customValue>
        <fullName>N95 Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Face Shields</fullName>
    </customValue>
    <customValue>
        <fullName>Hoods</fullName>
    </customValue>
    <customValue>
        <fullName>Level 3 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Level 4 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Coveralls</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Fit Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Nitrile)</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Sterile)</fullName>
    </customValue>
    <customValue>
        <fullName>Hand Sanitizer</fullName>
    </customValue>
    <customValue>
        <fullName>Disinfectant</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Goggles</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Glasses</fullName>
    </customValue>
    <customValue>
        <fullName>Shoe Covers</fullName>
    </customValue>
    <masterLabel>Status Report Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StatusReportsTest.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @description Test class for StatusReports
 * @author  Pedro Serquiz, Traction on Demand
 * @date    2020-03-25
 */
@IsTest
private with sharing class StatusReportsTest {
	//	@TestSetup
	//	static void setup() {
	//		Account account = TestUtils.createCommunityAccount('Test Account', FALSE);
	//		account.Beds_Available__c = 0;
	//		account.Beds_in_Use__c = 0;
	//		account.Beds_Inactive__c = 0;
	//		account.RecordTypeId = Constants.DIVISION_RECORDTYPE_ID;
	//		insert account;
	//
	//		Contact testContact = TestUtils.createCommunityContact('Test Contact', FALSE);
	//		testContact.AccountId = account.Id;
	//		insert testContact;
	//
	//		User communityUser = TestUtils.createCommunityUser(Constants.COMMUNITY_PROFILE_NAME, testContact.Id);
	//
	//		System.runAs(new User(Id = UserInfo.getUserId())){
	//			insert communityUser;
	//		}
	//	}
	//
	//	@IsTest
	//	static void test_afterInsertStatusReport() {
	//		User testUsr = [SELECT Id FROM User WHERE Profile.Name = :Constants.COMMUNITY_PROFILE_NAME ORDER BY CreatedDate DESC LIMIT 1];
	//		Account accountBeforeTriggerRuns = [SELECT Id, Beds_Available__c, Beds_in_Use__c, Beds_Inactive__c FROM Account LIMIT 1];
	//		//no data was created, all the values should be 0
	//		System.assertEquals(0, accountBeforeTriggerRuns.Beds_Available__c);
	//		System.assertEquals(0, accountBeforeTriggerRuns.Beds_in_Use__c);
	//		System.assertEquals(0, accountBeforeTriggerRuns.Beds_Inactive__c);
	//
	//		Test.startTest();
	//		System.runAs(testUsr) {
	//			insert new Status_Report__c(Name = 'test available', Count__c = 1, Status__c = StatusReportsHandler.AVAILABLE, Type__c = 'Ventilator Beds', Department__c = accountBeforeTriggerRuns.Id, Category__c = 'Equipment');
	//			insert new Status_Report__c(Name = 'test in use', Count__c = 2, Status__c = StatusReportsHandler.IN_USE, Type__c = 'Ventilator Beds', Department__c = accountBeforeTriggerRuns.Id, Category__c = 'Equipment');
	//			insert new Status_Report__c(Name = 'test inactive', Count__c = 3, Status__c = StatusReportsHandler.INACTIVE, Type__c = 'Ventilator Beds', Department__c = accountBeforeTriggerRuns.Id, Category__c = 'Equipment');
	//		}
	//		Test.stopTest();
	//
	//		Account accountAfterTriggerRuns = [SELECT Id, Beds_Available__c, Beds_in_Use__c, Beds_Inactive__c FROM Account LIMIT 1];
	//
	//		//after the trigger runs each of the types should have its own Count__c value
	//		System.assertEquals(1, accountAfterTriggerRuns.Beds_Available__c);
	//		System.assertEquals(2, accountAfterTriggerRuns.Beds_in_Use__c);
	//		System.assertEquals(3, accountAfterTriggerRuns.Beds_Inactive__c);
	//	}
	//
	//	@IsTest
	//	static void test_afterInsertStatusReportWithNoStatus() {
	//		User testUsr = [SELECT Id FROM User WHERE Profile.Name = :Constants.COMMUNITY_PROFILE_NAME ORDER BY CreatedDate DESC LIMIT 1];
	//		Account accountBeforeTriggerRuns = [SELECT Id, Beds_Available__c FROM Account LIMIT 1];
	//		//no data was created, all the values should be 0
	//		System.assertEquals(0, accountBeforeTriggerRuns.Beds_Available__c);
	//
	//		Test.startTest();
	//		System.runAs(testUsr) {
	//			insert new Status_Report__c(Name = 'test available', Count__c = 1, Type__c = 'Ventilator Beds', Department__c = accountBeforeTriggerRuns.Id, Category__c = 'Equipment');
	//		}
	//		Test.stopTest();
	//
	//		Account accountAfterTriggerRuns = [SELECT Id, Beds_Available__c FROM Account LIMIT 1];
	//
	//		//after the trigger runs, because no status was set, it shouldnt update the account
	//		System.assertEquals(0, accountAfterTriggerRuns.Beds_Available__c);
	//	}
}