force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>A unique external ID such as a hospital ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique external ID such as a hospital ID.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/Status_Report__c.object-meta.xml
<CustomObject>
    <description>Capture inventory for a given Department and patient details. New inventory items or patient statuses can be added and tracked depending on the need of the Department</description>
    <label>Status Report</label>
    <nameField>
        <label>Status Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Report__c/fields/Aggregate_Send_Error__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Send_Error__c</fullName>
    <label>Aggregate Send Error</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of data being tracked e.g. Equipment, Supplies</description>
    <inlineHelpText>The type of data being tracked</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Report_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>The amount of what you are tracking</description>
    <inlineHelpText>The amount</inlineHelpText>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <description>The time this was recorded</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The time this was recorded</inlineHelpText>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The location this status report is for.</description>
    <inlineHelpText>The location this status report is for.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Status Reports</relationshipLabel>
    <relationshipName>Status_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Is_Sent_To_Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Is_Sent_To_Aggregator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sent To Aggregator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Inactive can refer to a bed that&#39;s in an unstaffed ward and not available yet.</description>
    <inlineHelpText>Inactive can refer to a bed that&#39;s in an unstaffed ward and not available yet.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In use</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>These are the individual status report records by the core data point being tracked.</description>
    <inlineHelpText>These are the individual status report records by the core data point being tracked.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Report_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Report_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Patient</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Status Report Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Status_Report_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>COVID Like</fullName>
    </customValue>
    <customValue>
        <fullName>Presumptive COVID</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Positive</fullName>
        <label>COVID Positive</label>
    </customValue>
    <customValue>
        <fullName>Comorbidity</fullName>
    </customValue>
    <customValue>
        <fullName>Health Care Staff COVID Positive</fullName>
    </customValue>
    <customValue>
        <fullName>Age Range</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilator Beds</fullName>
    </customValue>
    <customValue>
        <fullName>Anaesthesia Machines</fullName>
    </customValue>
    <customValue>
        <fullName>N95 Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Face Shields</fullName>
    </customValue>
    <customValue>
        <fullName>Hoods</fullName>
    </customValue>
    <customValue>
        <fullName>Level 3 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Level 4 Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Coveralls</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Fit Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Surgical Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Masks</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Nitrile)</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves (Sterile)</fullName>
    </customValue>
    <customValue>
        <fullName>Hand Sanitizer</fullName>
    </customValue>
    <customValue>
        <fullName>Disinfectant</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Goggles</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Glasses</fullName>
    </customValue>
    <customValue>
        <fullName>Shoe Covers</fullName>
    </customValue>
    <masterLabel>Status Report Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IngressBatch.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @author  Pedro Serquiz, Traction on Demand
 * @date    2020-05-28
 */
global with sharing class IngressBatch implements Schedulable, Database.Batchable<SObject>, Database.AllowsCallouts {
	private static final Boolean IS_DATA_SHARING_ACTIVE = DataSharingSettingsController.getSettings().Is_Active__c;
	private static final String ENDPOINT_ASSETS = DataSharingSettingsController.getSettings().Endpoint__c+'assets';
	private static final String ENDPOINT_INFECTIONS = DataSharingSettingsController.getSettings().Endpoint__c+'infections';

	public Database.QueryLocator start(Database.BatchableContext BC){
		String queryString = 'SELECT Type__c, Status__c, Date_Time__c, Count__c, Category__c, Department__r.ShippingStreet, Department__r.ShippingCity, Department__r.ShippingCountry, ' +
				'Department__r.ShippingState, Department__r.ShippingPostalCode, Department__c, Department__r.Name, Department__r.Parent.ParentId, Department__r.Parent.Parent.Name, ' +
				'Department__r.ParentId, Department__r.Parent.Name, Department__r.BillingStreet, Department__r.BillingState, ' +
				'Department__r.External_ID__c, Department__r.Parent.Parent.External_ID__c, Department__r.Parent.External_ID__c, ' +
				'Department__r.BillingCountry, Is_Sent_To_Aggregator__c ' +
				'FROM Status_Report__c WHERE Is_Sent_To_Aggregator__c = false';
		return Database.getQueryLocator(queryString);
	}

	public void execute(Database.BatchableContext BC, List<Status_Report__c> statusReports){
		doExecute(statusReports);
	}

	@TestVisible
	private void doExecute(List<Status_Report__c> scope) {
		if (IS_DATA_SHARING_ACTIVE) {
			List<Status_Report__c> statusReportsToUpdate = new List<Status_Report__c>();
			for (Status_Report__c statusReport : scope) {
				if (statusReport.Category__c == 'Equipment' || statusReport.Category__c == 'Supplies') {
					IngressAsset asset = new IngressAsset(statusReport);
					Status_Report__c statusReportToUpdate = ingressRequest(asset.getJsonString(), statusReport.Id, ENDPOINT_ASSETS);
					statusReportsToUpdate.add(statusReportToUpdate);
				} else if (statusReport.Category__c == 'Patient') {
					IngressInfection infection = new IngressInfection(statusReport);
					Status_Report__c statusReportToUpdate = ingressRequest(infection.getJsonString(), statusReport.Id, ENDPOINT_INFECTIONS);
					statusReportsToUpdate.add(statusReportToUpdate);
				}
			}
			update statusReportsToUpdate;
		}
	}

	public static Status_Report__c ingressRequest(String jsonToSend, Id statusReportId, String endpoint) {
		HttpResponse response = IngressRestRequest.sendRequest(jsonToSend, endpoint);

		Status_Report__c statusReportToUpdate = new Status_Report__c(
				Id = statusReportId
		);

		//Write the appropriate fields
		switch on response.getStatusCode() {
			when 201, 204 {
				//If success then set the field to true
				statusReportToUpdate.Is_Sent_To_Aggregator__c = true;
			} when else {
				//If an error then populate the aggregate send error with the response body
				statusReportToUpdate.Aggregate_Send_Error__c = 'Error code '+response.getStatusCode()+': ' +response.getBody();
			}
		}
		return statusReportToUpdate;
	}

	public void execute(SchedulableContext ctx) {
		IngressBatch batchInstance = new IngressBatch();
		Database.executeBatch(batchInstance, 100);
	}
	public void finish(Database.BatchableContext BC) {}
}