force-app/main/default/objects/Account/fields/Health_Authority__c.field-meta.xml
<CustomField>
    <fullName>Health_Authority__c</fullName>
    <description>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</inlineHelpText>
    <label>Health Authority</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

force-app/main/default/objects/Staff_Access__c/Staff_Access__c.object-meta.xml
<CustomObject>
    <description>The staff assignments object is a junction object between Account and Contact, allowing a staff member to be assigned and multiple departments and access their data.</description>
    <label>Staff Access</label>
    <nameField>
        <label>Staff Access</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Access__c/fields/Care_Facility__c.field-meta.xml
<CustomField>
    <fullName>Care_Facility__c</fullName>
    <description>The care facility account the staff is being added to.</description>
    <inlineHelpText>Adding this staff member to this department or facility will share access to that department.</inlineHelpText>
    <label>Care Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>StaffAccess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staff_Access__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <description>The staff member to add to the department or facility.</description>
    <inlineHelpText>The staff member to add to the department or facility.</inlineHelpText>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff Access</relationshipLabel>
    <relationshipName>StaffAccess</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StaffAssignmentHandlerTest.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * Created by mmanik on 3/29/2020.
 */

@IsTest
private class StaffAssignmentHandlerTest {
//    public static Integer bulkNumber = 200;
//    public static Contact testContact;
//    public static User communityUser;
//    public static Account healthAuth;
//    public static Account hospital;
//
//    static {
//        healthAuth = TestUtils.createAccountByRecordType('TestAccount', Constants.HEALTH_AUTH_RECORDTYPE_ID, null, TRUE);
//        hospital = TestUtils.createAccountByRecordType('TestHospital', Constants.HOSPITAL_RECORDTYPE_ID, healthAuth.Id, FALSE);
//        hospital.Health_Authority__c = 'TestAuthority';
//        insert hospital;
//        testContact = TestUtils.createCommunityContact('Test Contact', FALSE);
//        testContact.AccountId = hospital.Id;
//        insert testContact;
//        communityUser = TestUtils.createCommunityUser(Constants.COMMUNITY_PROFILE_NAME, testContact.Id);
//        System.runAs(new User(Id = UserInfo.getUserId())) {
//            insert communityUser;
//        }
//    }
//
//    @IsTest
//    static void insertSharingForAccounts() {
//        // Query job sharing records.
//        List<AccountShare> accShares = AccountShareSelector.getAccountShares(healthAuth.Id, communityUser.Id);
//        System.assertEquals(0, accShares.Size(),'User must have no access record');
//        Staff_Access__c testAssignment = new Staff_Access__c(
//                Staff__c = testContact.Id,
//                Care_Facility__c = healthAuth.Id
//        );
//        Test.startTest();
//        insert testAssignment;
//        Test.stopTest();
//        accShares = AccountShareSelector.getAccountShares(healthAuth.Id, communityUser.Id);
//        System.assertEquals(1, accShares.Size(),'User must have no access record');
//        System.assertEquals(accShares[0].AccountAccessLevel, Constants.READ_ACCESS);
//    }
//
//    @IsTest
//    static void deleteSharingForAccounts() {
//        // Query job sharing records.
//        Staff_Access__c testAssignment = new Staff_Access__c(
//                Staff__c = testContact.Id,
//                Care_Facility__c = healthAuth.Id
//        );
//        insert testAssignment;
//        List<AccountShare> accShares = AccountShareSelector.getAccountShares(healthAuth.Id, communityUser.Id);
//        System.assertEquals(1, accShares.Size(),'User must have 1 access record');
//        Test.startTest();
//        delete testAssignment;
//        Test.stopTest();
//        accShares = AccountShareSelector.getAccountShares(healthAuth.Id, communityUser.Id);
//        System.assertEquals(0, accShares.Size(),'User must have no access record');
//    }
}