force-app/main/default/objects/Account/fields/Health_Authority__c.field-meta.xml
<CustomField>
    <fullName>Health_Authority__c</fullName>
    <description>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</inlineHelpText>
    <label>Health Authority</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Global__c.field-meta.xml
<CustomField>
    <fullName>Role_Global__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</description>
    <inlineHelpText>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On staff</fullName>
            </value>
            <value>
                <fullName>Isolation - COVID symptoms/exposure</fullName>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>COVID positive</fullName>
                <isActive>false</isActive>
                <label>COVID positive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_Access__c/Staff_Access__c.object-meta.xml
<CustomObject>
    <description>The staff assignments object is a junction object between Account and Contact, allowing a staff member to be assigned and multiple departments and access their data.</description>
    <label>Staff Access</label>
    <nameField>
        <label>Staff Access</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Access__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <description>Determines the type of access a Staff has to a Facility.</description>
    <inlineHelpText>Determines the type of access a Staff has to a Facility.</inlineHelpText>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_Access__c/fields/Care_Facility__c.field-meta.xml
<CustomField>
    <fullName>Care_Facility__c</fullName>
    <description>The care facility account the staff is being added to.</description>
    <inlineHelpText>Adding this staff member to this department or facility will share access to that department.</inlineHelpText>
    <label>Care Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>StaffAccess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staff_Access__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <description>The staff member to add to the department or facility.</description>
    <inlineHelpText>The staff member to add to the department or facility.</inlineHelpText>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff Access</relationshipLabel>
    <relationshipName>StaffAccess</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Update_Contact__c/Update_Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Update Contact</label>
</CustomObject>

force-app/main/default/objects/Update_Contact__c/fields/Number_of_days_Availaible__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_Availaible__c</fullName>
    <description>Used to set number of days of availability records on insert of new contact.</description>
    <label>Number of days Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Update_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Contains the roles for which we want to run trigger. Multiple roles can be separated with ; . If value in this filed is NULL then trigger will run for all roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD - Medical Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>RN - Registered Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>RT - Respiratory Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>NP - Nurse Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Registrant</fullName>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <description>Defines Staff roles at Facilities to allow for reporting by role</description>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestUtils.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @description Utility class containing shared methods for test classes
 * @author  Heather Purvis, Traction on Demand
 * @date    2020-03-18
 */

@IsTest
public class TestUtils {
    public static Account createCommunityAccount(String name, Boolean doInsert) {

        Account ret = new Account(
                Name = name,
                RecordTypeId = Constants.HOSPITAL_RECORDTYPE_ID,
                BillingState = 'BC',
                Health_Authority__c = 'Health Authority Test'
        );

        if(doInsert){
            insert ret;
        }

        return ret;
    }

    public static Account createHealthAuthority(String name, Boolean doInsert) {

        Account ret = new Account(
                Name = name,
                RecordTypeId = Constants.HEALTH_AUTH_RECORDTYPE_ID,
                BillingState = 'BC',
                Health_Authority__c = name
        );

        if(doInsert){
            insert ret;
        }

        return ret;
    }

    public static Account createHospital(String name, Id healthAuthorityId, Boolean doInsert) {
        String healthAuthName = [SELECT Id, Name FROM Account WHERE Id = :healthAuthorityId].Name;

        Account ret = new Account(
                Name = name,
                RecordTypeId = Constants.HOSPITAL_RECORDTYPE_ID,
                BillingState = 'BC',
                Health_Authority__c = healthAuthName,
                ParentId = healthAuthorityId
        );

        if(doInsert){
            insert ret;
        }

        return ret;
    }

    public static Account createAccountByRecordType(String name, Id RecordTypeId, Id parentId, Boolean doInsert) {

        Account ret = new Account(
                Name = name,
                RecordTypeId = RecordTypeId,
                ParentId = parentId,
                BillingState = 'BC'
        );

        if(doInsert){
            insert ret;
        }

        return ret;
    }

    public static Contact createCommunityContact(String name, Boolean doInsert) {
        Contact ret = new Contact(
                LastName = name,
                Role_Global__c = 'MD - Medical Doctor',
                Status__c = 'On staff'
        );

        if(doInsert){
            insert ret;
        }

        return ret;
    }

    public static List<Contact> createBulkContacts(Boolean doInsert, Integer numberOfContacts, Id AccountId) {
        List<Contact> contacts = new List<Contact>();
        for(Integer count = 0; count < numberOfContacts; count++){
            Contact thisContact = new Contact(
                    LastName = 'TestName' + count,
                    Role_Global__c = 'MD - Medical Doctor',
                    Status__c = 'On staff',
                    AccountId = AccountId
            );
            contacts.add(thisContact);
        }

        if(doInsert){
            insert contacts;
        }

        return contacts;
    }

    public static User createCommunityUser(String profileName, Id contactId) {
        Profile p = [SELECT Id, Name FROM Profile WHERE Name =: profileName];

        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueOf(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(Math.rint(Math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User u = new User(
                FirstName = 'test',
                LastName = 'test',
                Email = uniqueName + '@test' + orgId + '.org',
                Username = uniqueName + '@test' + orgId + '.org',
                EmailEncodingKey = 'ISO-8859-1',
                Alias = uniqueName.substring(18, 23),
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ProfileId = p.Id,
                IsActive = true,
                ContactId = contactId
        );
        return u;
    }

    public static User createAdminUser() {
        Profile p = [SELECT Id, Name FROM Profile WHERE Name =: 'System Administrator'];

        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueOf(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(Math.rint(Math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User u = new User(
                FirstName = 'test',
                LastName = 'test',
                Email = uniqueName + '@test' + orgId + '.org',
                Username = uniqueName + '@test' + orgId + '.org',
                EmailEncodingKey = 'ISO-8859-1',
                Alias = uniqueName.substring(18, 23),
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ProfileId = p.Id,
                IsActive = true
        );
        return u;
    }

    public static void insertContactCustomSettings(Boolean insertRoles) {
        Update_Contact__c setting = new Update_Contact__c();
        if(insertRoles){
            setting.Role__c = 'MD - Medical Doctor;RN - Registered Nurse';
        }
        setting.Number_of_days_Availaible__c = 14;
        insert setting;
    }

    public static Staff_Access__c createStaffAccess(Id contactId, Id facilityId, Boolean doInsert) {
        Staff_Access__c result = new Staff_Access__c(
                Name = 'N/A',
                Staff__c = contactId,
                Care_Facility__c = facilityId
        );

        if(doInsert){
            insert result;
        }

        return result;
    }

    public static Staff_Access__c createReadStaffAccess(Id contactId, Id facilityId, Boolean doInsert) {
        Staff_Access__c result = new Staff_Access__c(
                Name = 'N/A',
                Staff__c = contactId,
                Care_Facility__c = facilityId,
                Access_Level__c = Constants.READ_ACCESS
        );

        if(doInsert){
            insert result;
        }

        return result;
    }

    public static Staff_Access__c createEditStaffAccess(Id contactId, Id facilityId, Boolean doInsert) {
        Staff_Access__c result = new Staff_Access__c(
                Name = 'N/A',
                Staff__c = contactId,
                Care_Facility__c = facilityId,
                Access_Level__c = Constants.EDIT_ACCESS
        );

        if(doInsert){
            insert result;
        }

        return result;
    }
}