force-app/main/default/objects/Account/fields/Health_Authority__c.field-meta.xml
<CustomField>
    <fullName>Health_Authority__c</fullName>
    <description>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Text version of the top level health authority, system field for sharing rules. A workflow rule populates this field based on the facility hierarchy.</inlineHelpText>
    <label>Health Authority</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Availability keeps track of staff availability and allow users to assign staff to divisions</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Care_Facility__c.field-meta.xml
<CustomField>
    <fullName>Care_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Global__c.field-meta.xml
<CustomField>
    <fullName>Role_Global__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <inlineHelpText>Select the valid competencies</inlineHelpText>
    <label>Competencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>Critical Care</fullName>
            </value>
            <value>
                <fullName>IV Therapy</fullName>
            </value>
            <value>
                <fullName>Neonatal</fullName>
            </value>
            <value>
                <fullName>Perinatal</fullName>
            </value>
            <value>
                <fullName>Perioperative</fullName>
            </value>
            <value>
                <fullName>Nephrology/Dialysis</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>EPAC</fullName>
            </value>
            <value>
                <fullName>General GYN</fullName>
            </value>
            <value>
                <fullName>Obstetrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</description>
    <inlineHelpText>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On staff</fullName>
            </value>
            <value>
                <fullName>Isolation - COVID symptoms/exposure</fullName>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>COVID positive</fullName>
                <isActive>false</isActive>
                <label>COVID positive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD - Medical Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>RN - Registered Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>RT - Respiratory Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>NP - Nurse Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Registrant</fullName>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <description>Defines Staff roles at Facilities to allow for reporting by role</description>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactsSelector.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @description Selector class for contacts records
 * @author  Heather Purvis, Traction on Demand
 * @date    2020-03-23
 */
public with sharing class ContactsSelector {

    /**
     * @description Gets current user's contact info
     * @param       currentUser
     * @return      List of contacts
     */
    public static List<Contact> getCurrentContact(User currentUser) {
        List<Contact> currentContact = [
                SELECT Id,
                        Name,
                        Department,
                        Email,
                        MobilePhone,
                        Phone,
                        Skills__c,
                        toLabel(Skills__c) SkillLabel,
                        Role_Global__c,
                        toLabel(Role_Global__c) RoleGlobalLabel,
                        AccountId,
                        Account.Name,
                        Account.RecordTypeId,
                        Account.Health_Authority__c,
                        Account.Parent.Name,
                        Account.Parent.Id,
                        Account.Parent.Parent.Name,
                        Account.Parent.Parent.Id
                FROM Contact
                WHERE Id = :currentUser.ContactId
        ];
        return currentContact;
    }

    /**
     * @description Gets current user info
     * @return      User
     */
    public static User getCurrentUser() {
        User currentUser = [
                SELECT Id,
                        ContactId,
                        Contact.AccountId,
                        UserRole.Name,
                        Profile.Name,
                        SmallPhotoUrl,
                        FullPhotoUrl
                FROM User
                WHERE Id = :UserInfo.getUserId()
        ];

        return currentUser;
    }

    public static List<Contact> getContactsWithRelatedAssignments() {

        return [SELECT Id, Role_Global__c,
                    (select Date__c from Assignments__r WHERE Staff__c != NULL AND Date__c >= TODAY)
               FROM Contact];
    }

    public static List<Contact> getContactsWithRelatedUsers(Set<Id> contactIds) {
        return [SELECT Id, Name,
                    (select Id, Name from Users )
                FROM Contact    WHERE ID IN :contactIds];
    }

    public static List<Contact> selectContactById(Id contactId) {
        List<Contact> cont = [SELECT Id, FirstName, Status__c,toLabel(Status__c) StatusLabel, LastName, AccountId, Account.Name  FROM Contact WHERE Id = :contactId];
        return cont;
    }
}