force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Availability keeps track of staff availability and allow users to assign staff to divisions</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/User_Updated__c.field-meta.xml
<CustomField>
    <fullName>User_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Global__c.field-meta.xml
<CustomField>
    <fullName>Role_Global__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</description>
    <inlineHelpText>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On staff</fullName>
            </value>
            <value>
                <fullName>Isolation - COVID symptoms/exposure</fullName>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>COVID positive</fullName>
                <isActive>false</isActive>
                <label>COVID positive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Update_Contact__c/Update_Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Update Contact</label>
</CustomObject>

force-app/main/default/objects/Update_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Contains the roles for which we want to run trigger. Multiple roles can be separated with ; . If value in this filed is NULL then trigger will run for all roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD - Medical Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>RN - Registered Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>RT - Respiratory Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>NP - Nurse Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Registrant</fullName>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <description>Defines Staff roles at Facilities to allow for reporting by role</description>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvailabilityService.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * Created by mmanik on 3/26/2020.
 */

public with sharing class AvailabilityService {

    public static void createAvailabilityRecords(List<Contact> availableContacts) {
        List<Assignment__c> assignmentsToInsert = new List<Assignment__c>();
        Update_Contact__c contactSetting = Update_Contact__c.getInstance();
        List<String> roles = (contactSetting != NULL && contactSetting.Role__c != NULL) ? contactSetting.Role__c.split(';') : NULL;

        for(Contact thisContact : availableContacts){
            if(roles == NULL || roles.contains(thisContact.Role_Global__c)){
                Assignment__c thisAssignment = new Assignment__c(
                        Date__c = (thisContact.Assignments__r != null && thisContact.Assignments__r.size()>0 && thisContact.Assignments__r[0].Date__c != NULL)
                                                                    ? thisContact.Assignments__r[0].Date__c + 1 : Date.today(),
                        Available__c =  (thisContact.Status__c == Constants.NOT_AVAILABLE_STATUS)
                                                ? Constants.NOT_AVAILABLE_ASSIGNMENT_STATUS : Constants.AVAILABLE_ASSIGNMENT_STATUS,
                        Staff__c = thisContact.Id,
                        User_Updated__c = FALSE
                );
                assignmentsToInsert.add(thisAssignment);
            }
        }
        SecureDml insertObject = new SecureDml();
        insertObject.dmlInsert(assignmentsToInsert);
    }
}