force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Availability keeps track of staff availability and allow users to assign staff to divisions</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/User_Updated__c.field-meta.xml
<CustomField>
    <fullName>User_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role_Global__c.field-meta.xml
<CustomField>
    <fullName>Role_Global__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</description>
    <inlineHelpText>On Staff = available to work, Not Available = all future availability records will automatically be set to Not Available</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On staff</fullName>
            </value>
            <value>
                <fullName>Isolation - COVID symptoms/exposure</fullName>
                <label>Not Available</label>
            </value>
            <value>
                <fullName>COVID positive</fullName>
                <isActive>false</isActive>
                <label>COVID positive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Update_Contact__c/Update_Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Update Contact</label>
</CustomObject>

force-app/main/default/objects/Update_Contact__c/fields/Number_of_days_Availaible__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_Availaible__c</fullName>
    <description>Used to set number of days of availability records on insert of new contact.</description>
    <label>Number of days Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Update_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Contains the roles for which we want to run trigger. Multiple roles can be separated with ; . If value in this filed is NULL then trigger will run for all roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD - Medical Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>RN - Registered Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>RT - Respiratory Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>NP - Nurse Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Registrant</fullName>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <description>Defines Staff roles at Facilities to allow for reporting by role</description>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactHandler.cls
/*
    Copyright (c) 2020, Traction Sales And Marketing Inc.
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this List of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this List of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * @author  Manik, Traction on Demand
 * @date    2020-03-26
 */

public with sharing class ContactHandler {

    private List<Contact> contacts;
    private Map<Id, Contact> oldContacts;
    /**
    * @description          Constructor
    *
    * @param contacts     [Trigger.new Contacts]
    * @param oldContacts  [Trigger.oldMap Contacts]
    */
    public ContactHandler(List<Contact> contacts, Map<Id, Contact> oldContacts) {
        this.contacts = contacts;
        this.oldContacts = oldContacts;
    }

    public void createAssignments(){
       Update_Contact__c contactSetting = Update_Contact__c.getInstance();
        //This value is a backup value just in case if custom setting is not there If custom setting exist then it is not used.
        Integer numberOfAssignments = 14;
        List<String> roles = NULL;
        if(contactSetting != NULL){
            numberOfAssignments = Integer.valueOf(contactSetting.Number_of_days_Availaible__c);
            roles = (contactSetting.Role__c != null) ? contactSetting.Role__c.split(';') : NULL;
        }
        List<Assignment__c> assignments = new List<Assignment__c>();
        for(Contact thisContact : (List<Contact>)Trigger.New){
            if(roles == NULL || roles.contains(thisContact.Role_Global__c)){
                String status = (thisContact.Status__c == Constants.NOT_AVAILABLE_STATUS)
                                        ? Constants.NOT_AVAILABLE_ASSIGNMENT_STATUS : Constants.AVAILABLE_ASSIGNMENT_STATUS;
                createBulkAssignments(numberOfAssignments, thisContact.Id, assignments, status);
            }
        }
        SecureDml insertObject = new SecureDml();
        insertObject.dmlInsert(assignments);
    }

    private void createBulkAssignments(Integer numberOfAssignments, Id contactId, List<Assignment__c> assignments, String status) {
        for(Integer count = 0; count < numberOfAssignments; count++){
            Assignment__c thisAssignment = new Assignment__c(
                    Date__c = Date.today() + count,
                    Available__c = status,
                    Staff__c = contactId,
                    User_Updated__c = FALSE
            );
            assignments.add(thisAssignment);
        }
    }

    public void deleteAssignments(){
        List<Assignment__c> assignments = AvailabilitySelector.getAssignments(contacts);
        if(assignments.size()>0){
            SecureDml deleteObject = new SecureDml();
            deleteObject.dmlDelete(AvailabilitySelector.getAssignments(contacts));
        }
    }

    public void updateAssignments(){
        List<Contact> contactList = filterContactsWithStatusChange();
        Map<Id, Contact> filteredContactMap = new Map<Id, Contact>(contactList);
        List<Assignment__c> assignments = AvailabilitySelector.getFutureAssignments(contactList);
        for(Assignment__c thisAssignment : assignments){
            Contact relatedContact = filteredContactMap.get(thisAssignment.Staff__c);
            thisAssignment.Available__c = (relatedContact.Status__c == Constants.NOT_AVAILABLE_STATUS)
                                    ?  Constants.NOT_AVAILABLE_ASSIGNMENT_STATUS : Constants.AVAILABLE_ASSIGNMENT_STATUS;
        }
        if(assignments.size()>0){
            SecureDml updateObject = new SecureDml();
            updateObject.dmlUpdate(assignments);
        }
    }

    private List<Contact> filterContactsWithStatusChange() {
        List<Contact> contactList = new List<Contact>();
        for(Contact thisContact : contacts){
            Contact oldContact = oldContacts.get(thisContact.Id);
            if(oldContact.Status__c != thisContact.Status__c){
                contactList.add(thisContact);
            }
        }
        return contactList;
    }
}